# Generated by Django 3.0.8 on 2021-03-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
