# Generated by Django 3.0.8 on 2021-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0002_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='codePostal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
