# Generated by Django 3.0.8 on 2021-03-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0006_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ville',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pays',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
