# Generated by Django 3.0.8 on 2021-03-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0008_auto_20210322_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mark',
        ),
    ]
