# Generated by Django 3.0.8 on 2021-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0013_suivipost'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivipost',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
