# Generated by Django 3.0.8 on 2021-03-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0014_suivipost_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuiviPost',
        ),
    ]
