# Generated by Django 3.0.8 on 2021-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0015_delete_suivipost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
