# Generated by Django 3.0.8 on 2021-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0016_pro_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
