# Generated by Django 3.0.8 on 2021-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0017_auto_20210403_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Immobilier', 'Immobilier'), ('Véhicules', 'Véhicules'), ('Pour la maison et jardin', 'Pour la maison et jardin'), ('Loisirs et Divertissement', 'Loisirs et Divertissement'), ('Informatique et Multimedia', 'Informatique et Multimedia'), ('Emploi et Services', 'Emploi et Services'), ('Habillement et Bien Etre', 'Habillement et Bien Etre'), ('Enterprises', 'Enterprises')], max_length=60, null=True),
        ),
    ]
