# Generated by Django 3.0.8 on 2021-04-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0022_blog_coverimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
    ]
