# Generated by Django 3.0.8 on 2021-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0023_auto_20210422_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shortDescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
