# Generated by Django 3.0.8 on 2021-04-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0025_auto_20210424_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Immobilier', 'Immobilier'), ('Véhicules', 'Véhicules'), ('Vacances', 'Vacances'), ('Maison et jardin', 'Maison et jardin'), ('Multimedia', 'Multimedia'), ('Périculture', 'Périculture'), ('Habillement et Bien Etre', 'Habillement et Bien Etre'), ('Mode', 'Mode'), ('Loisirs', 'Loisirs'), ('Matériel Professionnels', 'Matériel Professionnels')], max_length=60, null=True),
        ),
    ]
