# Generated by Django 3.0.8 on 2021-04-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0029_auto_20210424_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='coverImg',
            new_name='cover',
        ),
    ]
