# Generated by Django 3.0.8 on 2021-04-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0030_auto_20210425_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shortDescription',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
