# Generated by Django 3.0.8 on 2021-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0031_auto_20210425_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='shortDescription',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
