# Generated by Django 3.0.8 on 2021-04-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0034_post_sub_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_sub',
            new_name='_type',
        ),
    ]
