# Generated by Django 3.0.8 on 2021-04-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0038_auto_20210426_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Véhicules', 'Véhicules'), ('Vélos', 'Vélos'), ('Trotinette éléctrique', '3-Trotinette éléctrique'), ('Immobilier', 'Immobilier'), ('Loisirs', 'Loisirs'), ('Jeu et jouets', 'Jeu et jouets'), ('Jeux vidéos et consoles', 'Jeux vidéos et consoles'), ('Collection', 'Collection'), ('Alimentation', 'Alimentation'), ('Mode', 'Mode'), ('Périculture', 'Périculture'), ('Multimédia High tech', 'Multimédia High tech'), ('Maison et jardin', 'Maison et jardin'), ('Matériel professionnel', 'Matériel professionnel'), ('Divers', 'Divers'), ('Autres', 'Autres')], max_length=60, null=True),
        ),
    ]
