# Generated by Django 3.0.8 on 2021-04-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0040_auto_20210426_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_type',
            new_name='sub_sub',
        ),
    ]
