# Generated by Django 3.0.8 on 2021-04-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0041_auto_20210426_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_sub',
            new_name='_type',
        ),
    ]
