# Generated by Django 3.0.8 on 2021-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0042_auto_20210426_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
