# Generated by Django 3.0.8 on 2021-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0045_auto_20210426_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
