# Generated by Django 3.0.8 on 2021-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0046_auto_20210427_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
    ]
