# Generated by Django 3.0.8 on 2021-04-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Minimaliste', '0047_auto_20210428_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
